name: justaudiobrokenonios
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  dio: ^3.0.10
  crypto: ^2.1.5
  path_provider: ^1.6.27
  just_audio: ^0.6.8
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true